let suggestions = [
    "Python",
    "Kotlin",
    "Java",
    "JavaScript",
    "NodeJS",
    "TypeScript",
    "Go",
    "Swift",
    "c",
    "c++",
    "PHP",
    "c#",
    "Ruby",
    "Perl",
    "Scala",
    "Arduino",
    "Pascal",
    "Microsoft .net",
    " HTML",
    " CSS",
];